//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.2.0
//     from Assets/script/touchControlle.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @TouchControlle : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @TouchControlle()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""touchControlle"",
    ""maps"": [
        {
            ""name"": ""touch"",
            ""id"": ""bbfc149b-a5b0-4ee7-a90c-f89c8d391b23"",
            ""actions"": [
                {
                    ""name"": ""touching"",
                    ""type"": ""PassThrough"",
                    ""id"": ""db419f80-13f4-4bfa-9b48-84c04dbbc5e7"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""a57fb325-fc7b-475c-b8ac-9d6ece52c215"",
                    ""path"": ""<Touchscreen>/primaryTouch"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""touching"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // touch
        m_touch = asset.FindActionMap("touch", throwIfNotFound: true);
        m_touch_touching = m_touch.FindAction("touching", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // touch
    private readonly InputActionMap m_touch;
    private ITouchActions m_TouchActionsCallbackInterface;
    private readonly InputAction m_touch_touching;
    public struct TouchActions
    {
        private @TouchControlle m_Wrapper;
        public TouchActions(@TouchControlle wrapper) { m_Wrapper = wrapper; }
        public InputAction @touching => m_Wrapper.m_touch_touching;
        public InputActionMap Get() { return m_Wrapper.m_touch; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(TouchActions set) { return set.Get(); }
        public void SetCallbacks(ITouchActions instance)
        {
            if (m_Wrapper.m_TouchActionsCallbackInterface != null)
            {
                @touching.started -= m_Wrapper.m_TouchActionsCallbackInterface.OnTouching;
                @touching.performed -= m_Wrapper.m_TouchActionsCallbackInterface.OnTouching;
                @touching.canceled -= m_Wrapper.m_TouchActionsCallbackInterface.OnTouching;
            }
            m_Wrapper.m_TouchActionsCallbackInterface = instance;
            if (instance != null)
            {
                @touching.started += instance.OnTouching;
                @touching.performed += instance.OnTouching;
                @touching.canceled += instance.OnTouching;
            }
        }
    }
    public TouchActions @touch => new TouchActions(this);
    public interface ITouchActions
    {
        void OnTouching(InputAction.CallbackContext context);
    }
}
